# Generated by Django 5.0.3 on 2024-03-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='vedio',
            field=models.FileField(null=True, upload_to='vedio/'),
        ),
    ]
