# Generated by Django 5.0.3 on 2024-03-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0002_form_vedio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='details',
        ),
    ]
