# Generated by Django 5.0.2 on 2024-03-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0003_rename_form_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
