# Generated by Django 5.0.3 on 2024-04-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0005_video_delete_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
